"""make credit_transactions amount and balance_after not null

Revision ID: d53941401e58
Revises: 121021f2b187
Create Date: 2026-03-10 21:00:17.385953

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d53941401e58"
down_revision: Union[str, None] = "121021f2b187"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("credit_transactions", schema=None) as batch_op:
        batch_op.alter_column("amount", existing_type=sa.NUMERIC(precision=12, scale=2), nullable=False)
        batch_op.alter_column("balance_after", existing_type=sa.NUMERIC(precision=12, scale=2), nullable=False)

    with op.batch_alter_table("daily_sku_summary", schema=None) as batch_op:
        batch_op.drop_index("idx_daily_sku_summary_store_product_date")
        batch_op.create_index(
            "idx_daily_sku_summary_store_product_date", ["store_id", "product_id", sa.text("date DESC")], unique=False
        )

    with op.batch_alter_table("daily_store_summary", schema=None) as batch_op:
        batch_op.drop_index("idx_daily_store_summary_store_date")
        batch_op.create_index("idx_daily_store_summary_store_date", ["store_id", sa.text("date DESC")], unique=False)

    with op.batch_alter_table("forecast_cache", schema=None) as batch_op:
        batch_op.alter_column("generated_at", existing_type=sa.TIMESTAMP(), nullable=False)
        batch_op.create_unique_constraint(
            "uq_forecast_cache_store_product_date", ["store_id", "product_id", "forecast_date"]
        )

    with op.batch_alter_table("loyalty_programs", schema=None) as batch_op:
        batch_op.alter_column(
            "is_active", existing_type=sa.BOOLEAN(), nullable=False, existing_server_default=sa.text("'true'")
        )

    with op.batch_alter_table("product_price_history", schema=None) as batch_op:
        batch_op.create_foreign_key(None, "stores", ["store_id"], ["store_id"])

    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.create_foreign_key(None, "hsn_master", ["hsn_code"], ["hsn_code"])

    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.drop_index("idx_transactions_store_created")
        batch_op.create_index("idx_transactions_store_created", ["store_id", sa.text("created_at DESC")], unique=False)
        batch_op.create_foreign_key(None, "staff_sessions", ["session_id"], ["id"])

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_foreign_key("fk_users_store_id", "stores", ["store_id"], ["store_id"], use_alter=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("fk_users_store_id", type_="foreignkey")

    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index("idx_transactions_store_created")
        batch_op.create_index("idx_transactions_store_created", ["store_id", "created_at"], unique=False)
        batch_op.drop_column("total_amount")

    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")

    with op.batch_alter_table("product_price_history", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")

    with op.batch_alter_table("loyalty_programs", schema=None) as batch_op:
        batch_op.alter_column(
            "is_active", existing_type=sa.BOOLEAN(), nullable=True, existing_server_default=sa.text("'true'")
        )

    with op.batch_alter_table("forecast_cache", schema=None) as batch_op:
        batch_op.drop_constraint("uq_forecast_cache_store_product_date", type_="unique")
        batch_op.alter_column("generated_at", existing_type=sa.TIMESTAMP(), nullable=True)

    with op.batch_alter_table("daily_store_summary", schema=None) as batch_op:
        batch_op.drop_index("idx_daily_store_summary_store_date")
        batch_op.create_index("idx_daily_store_summary_store_date", ["store_id", "date"], unique=False)

    with op.batch_alter_table("daily_sku_summary", schema=None) as batch_op:
        batch_op.drop_index("idx_daily_sku_summary_store_product_date")
        batch_op.create_index(
            "idx_daily_sku_summary_store_product_date", ["store_id", "product_id", "date"], unique=False
        )

    with op.batch_alter_table("credit_transactions", schema=None) as batch_op:
        batch_op.alter_column("balance_after", existing_type=sa.NUMERIC(precision=12, scale=2), nullable=True)
        batch_op.alter_column("amount", existing_type=sa.NUMERIC(precision=12, scale=2), nullable=True)

    # ### end Alembic commands ###
